# -*- coding: utf-8 -*-
"""Task1 Caesar cipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBEB5_pVkXEtbQvtEtE4-uo-t-U4z35h
"""

# Function to encrypt the text
def encrypt(text, shift):
    result = ""

    # Traverse the text
    for i in range(len(text)):
        char = text[i]

        # Encrypt uppercase letters
        if char.isupper():
            result += chr((ord(char) + shift - 65) % 26 + 65)

        # Encrypt lowercase letters
        elif char.islower():
            result += chr((ord(char) + shift - 97) % 26 + 97)

        # For other characters (spaces, punctuation), don't change them
        else:
            result += char

    return result

# Function to decrypt the text
def decrypt(text, shift):
    return encrypt(text, -shift)

# Main program
def main():
    # Ask the user for input
    choice = input("Do you want to (E)ncrypt or (D)ecrypt? ").upper()
    message = input("Enter your message: ")
    shift = int(input("Enter the shift value: "))

    if choice == 'E':
        print("Encrypted message: ", encrypt(message, shift))
    elif choice == 'D':
        print("Decrypted message: ", decrypt(message, shift))
    else:
        print("Invalid choice, please select 'E' or 'D'.")

if __name__ == "__main__":
    main()

# Function to encrypt the text
def encrypt(text, shift):
    result = ""

    # Traverse the text
    for i in range(len(text)):
        char = text[i]

        # Encrypt uppercase letters
        if char.isupper():
            result += chr((ord(char) + shift - 65) % 26 + 65)

        # Encrypt lowercase letters
        elif char.islower():
            result += chr((ord(char) + shift - 97) % 26 + 97)

        # For other characters (spaces, punctuation), don't change them
        else:
            result += char

    return result

# Function to decrypt the text
def decrypt(text, shift):
    return encrypt(text, -shift)

# Main program
def main():
    # Ask the user for input
    choice = input("Do you want to (E)ncrypt or (D)ecrypt? ").upper()
    message = input("Enter your message: ")
    shift = int(input("Enter the shift value: "))

    if choice == 'E':
        print("Encrypted message: ", encrypt(message, shift))
    elif choice == 'D':
        print("Decrypted message: ", decrypt(message, shift))
    else:
        print("Invalid choice, please select 'E' or 'D'.")

if __name__ == "__main__":
    main()